Preload is not always high priority
w3c/preload pull request #128
Opened 2018-08-17 16:15 UTC by domfarolino

Seems that https://github.com/w3c/preload/pull/53 added the "relationship to prefetch" note, which mentions prioritization that is not always true/backed by the spec. A lot of people are confused that preload is always fetched with high priority, but this isn't always this case, and since priorities are not standardized, I'm not sure if we can really include that.

I've included text indicating that prefetch is "often" low-priority, but if we want to remove any trace of prioritization from there too I'm happy to do that as well.

Fixes https://github.com/w3c/preload/issues/125. /cc @yoavweiss

2018-08-17 17:27 UTC, plehegar commented
Marked as non substantive for IPR from ash-nazg.

2018-08-20 08:10 UTC, yoavweiss requested changes

2018-08-20 08:10 UTC, yoavweiss commented on index.html
>      might be used by a subsequent navigation; `preload` is a mandatory and
s/mandatory and fetch/mandatory fetch/

2018-08-20 08:11 UTC, yoavweiss commented
@domfarolino Thanks for fixing that! One small nit

2018-08-23 09:23 UTC, yoavweiss approved these changes
LGTM

2018-08-23 09:23 UTC, merged

2018-08-29 11:38 UTC, gtsiolis commented
Thanks for fixing this @domfarolino! This is much clearer now.